### ISSUE TITLE
Better way of disabling Nav Menus in Customizer

### ISSUE THREAD

**Issue by erikjoling** [senlin/so-customizer-hide-menu#1]
Hi Pieter,

I see your plugin hides the Menu Panel in the Customizer through CSS. Wouldn't it be better to just remove the panel?

- https://wordpress.stackexchange.com/a/250368/133100
- https://developer.wordpress.org/reference/hooks/customize_loaded_components/

**Comment by senlin** [comment]
Hi Erik,
Thanks for the suggestion, that seems a lot better way of doing it than how it is done at the moment in the plugin.
